server {
    listen 80;
    server_name altupe.alhassan.life localhost;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API requests to backend
    location /api/ {
        client_max_body_size 500M;
        proxy_pass http://backend:8047/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy Mautic requests to bypass ad blockers
    location /mautic/ {
        proxy_pass http://mautic_web/;
        proxy_set_header Host mautic.alhassan.life;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
