version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/code/app
      - ~/.config/gcloud:/root/.config/gcloud
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
